bd/config/routes.rb
Rails.application.routes.draw do
  get 'home/dashboard'
  get 'cars/index'
  resources :cars
  resources :people
  root 'home#dashboard'
end

bd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bd/app/models/car.rb
class Car < ApplicationRecord
end

bd/app/models/person.rb
class Person < ApplicationRecord
end

bd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bd/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

bd/app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all
    end

    def show
        @car = Car.find(params[:id])
    end

    def new
        @car = Car.new
    end

    def create
        @car = Car.new(car_params)
        if @car.save
            redirect_to car_path(@car)
        else
            render :new
        end
    end

    def edit
        @car = Car.find(params[:id])
    end

    def update
        @car = Car.find(params[:id])
        if @car.update(car_params)
            redirect_to car_path(@car)
        else
            render :edit
        end
    end

    private

    def car_params
        params.require(:car).permit(:placa, :color, :modelo, :propietario)
    end
end

bd/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

bd/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

bd/app/controllers/people_controller.rb
class PeopleController < ApplicationController
    def index
        @person = Person.all
    end

    def show
        @person = Person.find(params[:id])
    end

    def new
        @person = Person.new
    end

    def create
        @person = Person.new(person_params)
        if @person.save
            redirect_to person_path(@person)
        else
            render :new
        end
    end

    def edit
        @person = Person.find(params[:id])
    end

    def update
        @person = Person.find(params[:id])
        if @person.update(person_params)
            redirect_to person_path(@person)
        else
            render :edit
        end
    end

    private

    def person_params
        params.require(:person).permit(:nombre, :identificacion, :genero, :estado)
    end
end

bd/app/helpers/application_helper.rb
module ApplicationHelper
end

bd/app/helpers/articles_helper.rb
module ArticlesHelper
end

bd/app/helpers/cars_helper.rb
module CarsHelper
end

bd/app/helpers/home_helper.rb
module HomeHelper
end

bd/app/helpers/homes_helper.rb
module HomesHelper
end

bd/app/helpers/people_helper.rb
module PeopleHelper
end

bd/app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

bd/app/views/cars/_car.html.erb
<% @cars.each do |car|%>
    <tr>
        <th scope="row"><%= car.id %></th>
        <td>
            <%= link_to car.placa, car_path(car.id) %>
        </td>
        <td><%= car.color %></td>
        <td><%= car.modelo %></td>
        <td><%= car.propietario %></td>
    </tr>
<% end %>

bd/app/views/cars/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for @car do |f| %>

        <%= f.input :placa %>
        <%= f.input :color %>
        <%= f.input :modelo %>
        <%= f.input :propietario %>

        <%= f.button :submit %>
    <% end %>
  </div>
</div>

bd/app/views/cars/edit.html.erb
<h1>Editar Carro</h1>

<%= render 'form', car: @car %>
<%= link_to 'Ver registro', @car %> |
<%= link_to 'Regresar', cars_path %>

bd/app/views/cars/index.html.erb
<h1>Lista de carros</h1>

<table class= "table">
  <thead class="table table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Placa</th>
      <th scope="col">Color</th>
      <th scope="col">Modelo</th>
      <th scope="col">Propietario</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'car' %>
  </tbody>
  
</table>

<%= link_to "agregar carro", new_car_path %> 

bd/app/views/cars/new.html.erb
<h1>Formulario</h1>

<%= render 'form' %>

bd/app/views/cars/show.html.erb
<h1>Carro</h1>

<dl>
    <dt>Placa</dt>
    <dd><%= @car.placa %></dd>
    <dt>Color</dt>
    <dd><%= @car.color %></dd>
    <dt>Modelo</dt>
    <dd><%= @car.modelo %></dd>
    <dt>Propietario</dt>
    <dd><%= @car.propietario %></dd>
</dl>

<%= link_to "lista de carros", cars_index_path %> |
<%= link_to "Editar", edit_car_path(@car) %> 

bd/app/views/home/dashboard.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

bd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to "Inicio", home_dashboard_path, class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <main class="container">
      <section class="row">
        <aside class="col-md-4">
          <div class="list-group">
            <%= link_to "Carros", cars_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "Personas", people_path, class: "list-group-item list-group-item-action" %>
          </div>
        </aside>
        <article class="col-md-8">
          <%= yield %>
        </article>
      </section>
    </main>
    



    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>

bd/app/views/people/_form.html.erb
<div class="row">
  <div class="col-md-6">  
  <%= simple_form_for @person do |f| %>

      <%= f.input :nombre %>
      <%= f.input :identificacion %>
      <%= f.input :genero %>
      <%= f.input :estado %>

      <%= f.button :submit %>
  <% end %>
</div>

bd/app/views/people/_person.html.erb
<% @person.each do |person|%>
    <tr>
        <th scope="row"><%= person.id %></th>
        <td>
            <%= link_to person.identificacion, person_path(person.id) %>
        </td>
        <td><%= person.nombre %></td>
        <td><%= person.genero %></td>
        <td><%= person.estado %></td>
    </tr>
<% end %>

bd/app/views/people/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form', person: @person %>
<%= link_to 'Ver registro', @person %> |
<%= link_to 'Regresar', person_path %>

bd/app/views/people/index.html.erb
<h1>Lista de usuarios</h1>

<table class="table">
  <thead class="table table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Identificación</th>
      <th scope="col">Genero</th>
      <th scope="col">Estado</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'person' %>
  </tbody>
  
</table>

<%= link_to "Agregar usuario", new_person_path %> 

bd/app/views/people/new.html.erb
<h1>Formulario</h1>

<%= render 'form' %>

bd/app/views/people/show.html.erb
<h1>Usuario</h1>

<dl>
    <dt>Nombre</dt>
    <dd><%= @person.nombre %></dd>
    <dt>Identificacion</dt>
    <dd><%= @person.identificacion %></dd>
    <dt>Genero</dt>
    <dd><%= @person.genero %></dd>
    <dt>Estado</dt>
    <dd><%= @person.genero %></dd>
</dl>

<%= link_to "lista de usuarios", people_path %> |
<%= link_to "Editar", edit_person_path(@person) %> 